spring.application.name=UBAKA
spring.datasource.url=jdbc:mysql://localhost:3306/ubaka_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Enable colorful console output
spring.output.ansi.enabled=always

# Default Security Credentials
spring.security.user.name=admin
spring.security.user.password=admin123

